### ISSUE TITLE
Adding chartutils breaks CV

### ISSUE THREAD

**Issue by suanto** [microsoft/powerbi-visuals-utils-chartutils#27]
Adding chartutils to Custom Visual produces Uncaught TypeError before anything is drawn to visual.

1. Create new Custom Visual with pbiviz-tool.
1. Add chartutils as instructed by the installation guide.
    1. Run npm install
    1. Add lines to pbiviz.json, tsconfig.json and visual.less
1. Add also @types/d3 and powerbi-models, because component will not compile without after chartutils added.
1. Custom Visual now compiles ok.
1. When accessing it in debug mode in powerbi-portal produces following error:

>Uncaught TypeError: Cannot read property 'DateTimeSequence' of undefined
>at chart.axis.chart.axis (<anonymous>:4274:83)
>    at utils.chart.utils.chart (<anonymous>:5486:19)
>    at extensibility.utils.extensibility.utils (<anonymous>:5487:15)
>    at powerbi.extensibility.powerbi.extensibility (<anonymous>:5488:11)
>    at powerbi (<anonymous>:5489:7)
>    at Window.<anonymous> (<anonymous>:5490:3)
>    at <anonymous>:8129:20
>    at Object.i [as injectJsCode] (VM581 visualhostcore.min.js:2)
>    at i.loadWithoutResourcePackage (VM582 visualsandbox.min.js:1)
>    at i.executeMessage (VM582 visualsandbox.min.js:1)

Custom Visual remains blank.

Using 
>powerbi-visuals-tools@1.11.3
and
>+-- @types/d3@3.5.39
+-- powerbi-models@1.0.3
+-- powerbi-visuals-utils-chartutils@1.5.1
| +-- d3@3.5.5
| +-- globalize@0.1.0-a2
| +-- powerbi-visuals-utils-formattingutils@2.1.0
| +-- powerbi-visuals-utils-interactivityutils@1.0.0
| +-- powerbi-visuals-utils-svgutils@1.1.0
| `-- powerbi-visuals-utils-typeutils@1.1.0
`-- powerbi-visuals-utils-dataviewutils@1.2.0

Any ideas what I'm doing wrong, or is there some problem with chartutils?

**Comment by uve** [comment]
@suanto, have you added the following js files?
https://github.com/Microsoft/powerbi-visuals-mekkochart/blob/master/pbiviz.json#L26-L33

**Comment by suanto** [comment]
@uve That seems to help, thanks!

Maybe you should update the documents?
https://github.com/Microsoft/powerbi-visuals-utils-chartutils/blob/master/docs/usage/installation-guide.md
