### ISSUE TITLE
Legend does not work in IE

### ISSUE THREAD

**Issue by suanto** [microsoft/powerbi-visuals-utils-chartutils#39]
Windows 10, Internet Explorer 11

Calling ILegend:drawLegend() fails.  Console has following error:
"ERROR TypeError: Permission denied"

Debugging this issue revealed that drawLegend calls drawLegendInternal and it in turn tries to call SVGElement::getElementsByClassName which seems to be undefined in Internet Explorer.

This bug prevents Legend from being drawn.

**Comment by helen508light** [comment]
it seems like it has already been fixed
