### ISSUE TITLE
drawLegend method doesn't work in IE11

### ISSUE THREAD

**Issue by GreyYar** [microsoft/powerbi-visuals-utils-chartutils#71]
Win10 b1909, Internet Explorer 11 v11.476.18362.0

`drawLegend` method fails to drow the Legend. The console does not display that problem.

Debugging shows that the `Symbol` object is not defined in IE. This object is used in "for..of" loops that also not supported by IE. Possible solution here might be to use classic "for" loop instead.  

Links:
* [drawLegend method](https://github.com/microsoft/powerbi-visuals-utils-chartutils/blob/master/src/legend/svgLegend.ts#L254 ) 
* [Symbol.iterator MDN description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator)

**Comment by helen508light** [comment]
In our visuals' code we use https://www.npmjs.com/package/core-js because of polyfills, you should do the same
It is not included in each utils code, because it can be used only once in visual's code
